// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

namespace backend.Migrations
{
    [DbContext(typeof(CvecaraContext))]
    [Migration("20210925202502_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("backend.Models.Buket", b =>
                {
                    b.Property<int>("buketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("buketID")
                        .UseIdentityColumn();

                    b.Property<int>("cenaBuketa")
                        .HasColumnType("int")
                        .HasColumnName("cenaBuketa");

                    b.Property<string>("nazivBuketa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nazivBuketa");

                    b.Property<int?>("policaID")
                        .HasColumnType("int");

                    b.HasKey("buketID");

                    b.HasIndex("policaID");

                    b.ToTable("Buket");
                });

            modelBuilder.Entity("backend.Models.Cvet", b =>
                {
                    b.Property<int>("cvetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cvetID")
                        .UseIdentityColumn();

                    b.Property<string>("bojaCveta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bojaCveta");

                    b.Property<int?>("buketID")
                        .HasColumnType("int");

                    b.Property<int>("cenaCveta")
                        .HasColumnType("int")
                        .HasColumnName("cenaCveta");

                    b.Property<int>("kolicinaCveta")
                        .HasColumnType("int")
                        .HasColumnName("kolicinaCveta");

                    b.Property<string>("nazivCveta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nazivCveta");

                    b.HasKey("cvetID");

                    b.HasIndex("buketID");

                    b.ToTable("Cvet");
                });

            modelBuilder.Entity("backend.Models.Polica", b =>
                {
                    b.Property<int>("policaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("policaID")
                        .UseIdentityColumn();

                    b.Property<int>("kapacitet")
                        .HasColumnType("int")
                        .HasColumnName("kapacitet");

                    b.Property<string>("nazivPolice")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nazivPolice");

                    b.Property<string>("opisPolice")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("opisPolice");

                    b.HasKey("policaID");

                    b.ToTable("Polica");
                });

            modelBuilder.Entity("backend.Models.PripadaBuketu", b =>
                {
                    b.Property<int>("buketID")
                        .HasColumnType("int")
                        .HasColumnName("buketID");

                    b.Property<int>("cvetID")
                        .HasColumnType("int")
                        .HasColumnName("cvetID");

                    b.Property<int>("kolicina")
                        .HasColumnType("int")
                        .HasColumnName("kolicina");

                    b.HasKey("buketID", "cvetID");

                    b.HasIndex("cvetID");

                    b.ToTable("PripadaBuketu");
                });

            modelBuilder.Entity("backend.Models.Buket", b =>
                {
                    b.HasOne("backend.Models.Polica", "polica")
                        .WithMany("buketiNaPolici")
                        .HasForeignKey("policaID");

                    b.Navigation("polica");
                });

            modelBuilder.Entity("backend.Models.Cvet", b =>
                {
                    b.HasOne("backend.Models.Buket", null)
                        .WithMany("cvetovi")
                        .HasForeignKey("buketID");
                });

            modelBuilder.Entity("backend.Models.PripadaBuketu", b =>
                {
                    b.HasOne("backend.Models.Buket", "buket")
                        .WithMany()
                        .HasForeignKey("buketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cvet", "cvet")
                        .WithMany()
                        .HasForeignKey("cvetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("buket");

                    b.Navigation("cvet");
                });

            modelBuilder.Entity("backend.Models.Buket", b =>
                {
                    b.Navigation("cvetovi");
                });

            modelBuilder.Entity("backend.Models.Polica", b =>
                {
                    b.Navigation("buketiNaPolici");
                });
#pragma warning restore 612, 618
        }
    }
}
